const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Audio,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Delete,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{logo: 0},
	{arkaplan: 0},
	{val: 0},
	{posX: 0},
	{posY: 0},
	{isFill: 0},
	{polar: 0},
	{apolar: 0},
	{iyon: 0},
	{etkilesim1: 0},
	{Flash: 0},
	{olumlu: 0},
	{bag: 0},
	{value: 0},
	{completed: 0},
	{molekulType: 0},
	{answerBox: 0},
	{molekul0: 0},
	{molekul1: 0},
	{molekul2: 0},
	{molekul3: 0},
	{molekul4: 0},
	{molekul5: 0},
	{molekul6: 0},
	{molekul7: 0},
	{molekul8: 0},
	{molekul9: 0},
	{molekul10: 0},
	{molekul11: 0},
	{molekul12: 0},
	{molekul13: 0},
	{molekul14: 0},
	{molekul15: 0},
	{molekul16: 0},
	{molekul17: 0},
	{molekul18: 0},
	{randomArray: 0},
	{AJAX: 0},
	{etkilesimJSON: 0},
	{etkilesim2: 0},
	{etkilesim3: 0},
	{etkilesim4: 0},
	{etkilesim5: 0},
	{isActive: 0},
	{nextBtn: 0},
	{prevBtn: 0},
	{Audio: 0},
	{olumsuz: 0},
	{molekuller: 0},
	{DragDrop: 0},
	{types: 0},
	{etkilesimItems: 0},
	{checkControl: 0},
	{animStart: 0},
	{answerUID: 0},
	{molekulTypeControl: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	polar: class extends self.ISpriteInstance {},
	apolar: class extends self.ISpriteInstance {},
	iyon: class extends self.ISpriteInstance {},
	etkilesim1: class extends self.ISpriteInstance {},
	olumlu: class extends self.ISpriteInstance {},
	bag: class extends self.ISpriteInstance {},
	molekulType: class extends self.ISpriteInstance {},
	answerBox: class extends self.ISpriteInstance {},
	molekul0: class extends self.ISpriteInstance {},
	molekul1: class extends self.ISpriteInstance {},
	molekul2: class extends self.ISpriteInstance {},
	molekul3: class extends self.ISpriteInstance {},
	molekul4: class extends self.ISpriteInstance {},
	molekul5: class extends self.ISpriteInstance {},
	molekul6: class extends self.ISpriteInstance {},
	molekul7: class extends self.ISpriteInstance {},
	molekul8: class extends self.ISpriteInstance {},
	molekul9: class extends self.ISpriteInstance {},
	molekul10: class extends self.ISpriteInstance {},
	molekul11: class extends self.ISpriteInstance {},
	molekul12: class extends self.ISpriteInstance {},
	molekul13: class extends self.ISpriteInstance {},
	molekul14: class extends self.ISpriteInstance {},
	molekul15: class extends self.ISpriteInstance {},
	molekul16: class extends self.ISpriteInstance {},
	molekul17: class extends self.ISpriteInstance {},
	molekul18: class extends self.ISpriteInstance {},
	randomArray: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	etkilesimJSON: class extends self.IJSONInstance {},
	etkilesim2: class extends self.ISpriteInstance {},
	etkilesim3: class extends self.ISpriteInstance {},
	etkilesim4: class extends self.ISpriteInstance {},
	etkilesim5: class extends self.ISpriteInstance {},
	nextBtn: class extends self.ISpriteInstance {},
	prevBtn: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	olumsuz: class extends self.ISpriteInstance {},
	molekuller: class extends self.ISpriteInstance {},
	types: class extends self.ISpriteInstance {},
	etkilesimItems: class extends self.ISpriteInstance {}
}